### PR TITLE
Change the way to render empty component

### PR DESCRIPTION
**Pull request by snehilvj**
Started facing an issue recently with null/undefined component props in dmc. Upon investigating, found this to be the issue. Although this fixes the issue, I did not investigate why it's become an issue only recently. Nevertheless, I think this should be the correct way to render "nothing".

### CODE REVIEW

**Comment by emilhe** [comment]
The condition that you want to change originates from here,

https://github.com/plotly/dash/blob/c313d1b1c5aba054073b4925122accef5642ce5d/dash/dash-renderer/src/TreeContainer.js#L187

Since `isNill` handles fewer cases than `isEmpty`  (e.g. not empty list), I am not sure this change is a good idea. But I guess it would be fine to include `undefined` (which I assume is causing your issue? Otherwise, please post a MWE) either explicitly or via a `isNill`  in a chained condition, e.g.
```
    if (isNil(component) || isEmpty(component)) {
        return null;
    }
```
What do you think about that?

**Comment by snehilvj** [comment]
Why do you think this issue started coming up in the first place? All the other components that used to work before have stopped working because they fail here. I'm surprised this worked before as isEmpty is supposed to return false for both null and undefined values.
As far as MWE is concerned, most of the components in the latest dmc master are not working.

PS: I'll make your suggested change in the PR. But I'd still like to know what's happening here.

**Comment by emilhe** [comment]
I have no idea why the behavior should change. I didn't change anything from my side, and so far I haven't seen any issues. Maybe some other external library was updated?

**Comment by snehilvj** [comment]
yeah I did update a lot of dependencies including Mantine, not sure which one could have caused this. Anyway I'll investigate this when I get a chance and will update you as well.

**Comment by emilhe** [comment]
While I am still curious, if it works now, I don't think it's a big issue. As I read the code, the only logical difference after this PR is that components with value `undefined` now render as empty. That seems reasonable to me.

**Pull request merged**
